app:
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    averageValue: 80
  ingressClass: nginx
  url: qasem2.balouli.com
  whitelist: "0.0.0.0/0"
  image: 907244240513.dkr.ecr.eu-central-1.amazonaws.com/backend:latest
  env: dev

resources:
  app:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 128Mi
