name: Build and Push Docker Images

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-central-1
  BUILDX_VERSION: ${{ github.sha }}
  IMAGE_TAG: latest
  ECR_REPOSITORY: backend
  ECR_REGISTRY: '907244240513.dkr.ecr.eu-central-1.amazonaws.com'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get TAG
        id: get_tag
        run: echo TAG=${GITHUB_REF#refs/tags/} >> $GITHUB_ENV

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
    
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 🔑 Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: backend
        with:
          images: |
            images: $ECR_REGISTRY/$ECR_REPOSITORY,enable=true
          tags: |
            type=semver,pattern={{version}},value=$BUILDX_VERSION

      - name: 🐳 Docker Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          platforms: linux/amd64
          #tags: ${{ steps.meta.outputs.tags }}
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            Version=${{  env.TAG }}
            BUILD_DATE=$(date +%s)
            GitCommit=${{ github.sha }}
